version: 2

models:
  - name: stg_fixtures
    columns:
      - name: fixture_id
        tests: [not_null, unique]
      - name: kickoff_at
        tests: [not_null]
      - name: home_team_id
        tests: [not_null]
      - name: away_team_id
        tests: [not_null]
  - name: mart_daily_fixtures
    columns:
      - name: fixture_id
        tests: [not_null, unique]

